FROM python:3.12

# Set the working directory in the container
WORKDIR /app

COPY requirements.txt .
COPY emulator.py .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "emulator.py"]